A = input('Digite algo: ')
print ('O tipo primitivo desse valor é {}'.format(type(A)))
print ('Só tem espaços? {}'.format(A.isspace()))
print ('É um número? {}'.format(A.isnumeric()))
print ('É alfabético? {}'.format(A.isalpha()))
print ('É alfanumérico? {}'.format(A.isalnum()))
print ('Está em maiúsculas? {}'.format(A.isupper()))
print ('Está em minúsculas? {}'.format(A.islower()))
print ('Está capitalizada? {}'.format(A.istitle()))